### PR TITLE
feat(vault): adjust matrix to add `3000.1` & remove `2017.7`

### PR DESCRIPTION
**Pull request by dafyddj**
Is this PR correct?

I'm having some trouble with the git scripts, so in the interest of keeping things moving could you apply this change to the vault formula? Thanks

### CODE REVIEW

**Comment by myii** [comment]
@dafyddj Thanks for taking this on, looks good from here.  Let me try it out at my end and I'll let you know.

**Comment by myii** [comment]
Actually, I was looking forward to this opportunity: I want to make sure that the person who makes the commit gets carried over as the author of the commit made in the affected formula(s).  Let's make sure that happens here.

**Comment by myii** [comment]
Testing out the build after the changes have been applied:

* https://travis-ci.org/github/myii/vault-formula/builds/673012827

Now to figure out how to get the author's details.  Cop-out option is to simply set it via. pillar.  Might be the right thing to do at first...

**Comment by myii** [comment]
> https://travis-ci.org/github/myii/vault-formula/builds/673012827

All passing, the diff looks good in the `vault-formula`.

> I'm having some trouble with the git scripts, ...

Those scripts are ugly hacks that I've always intended to replace with the relevant git states and modules, as much as possible.

**Comment by dafyddj** [comment]
> Those scripts are ugly hacks that I've always intended to replace with the relevant git states and modules, as much as possible.

I didn't want to say anything 😉; but, no, just some more Mac incompatibilities although I did try things in a Linux Vagrant box too and encountered some other issue.
I do think we could build out something more robust, starting with some testing first.

**Comment by myii** [comment]
> I didn't want to say anything wink; but, no, just some more Mac incompatibilities although I did try things in a Linux Vagrant box too and encountered some other issue.

I knew what you were thinking!  Just needed to get something out there when the number of `semantic-release` formulas became unmanageable.  Alongside being a quick fix, my approach towards this whole formula has been using it as a fact-finding project.  If we ever get around to preparing a proper solution, there's a lot to be learnt from what's been mapped out here.

> I do think we could build out something more robust, starting with some testing first.

I did think a lot about testing when I first started out but I didn't get around to figuring out how to actual verify the changes being pushed to actual (test) GitHub repos.  There's always the first stage of at least testing modifications to target repos made locally.

**Comment by myii** [comment]
@dafyddj OK, got it working via. 659a768 -- not my proudest moment and another reason to shift away from the shell scripts.  Pushed and created the PR automatically, all looking good otherwise.  My usual method is to merge this after the propagated commits/PRs are merged.

**Comment by dafyddj** [comment]
Thanks. Just let me do some manual testing.

**Comment by myii** [comment]
Landmark moment, first PR merged into this repo from someone other than myself -- thanks for that.

**Pull request merged**
