### PR TITLE
feat(gitignore): track TOFS override files (`salt` & `template`)

### PR DESCRIPTION
**Pull request by myii**
* https://github.com/saltstack-formulas/salt-formula/pull/444
* https://github.com/saltstack-formulas/template-formula/pull/189

### CODE REVIEW

**Comment by dafyddj** [comment]
@myii do you agree that `.bundle/` should be added to all formulas?

**Comment by myii** [comment]
@dafyddj Sure, I've just used this PR as a stop-gap before merging all of these into one `.gitignore` (short of time right now to run against all of the formulas).  Do you agree with the changes in the `salt-formula` as well (the last few lines)?

**Comment by dafyddj** [comment]
Is it worth being explicit that `.vagrant/` is a dir?
I don't recall coming across a `top.sls` myself. What is that used for?

**Comment by myii** [comment]
We'd have to ask @MSeven what the rationale is.  I wasn't involved in that PR's review.

**Comment by dafyddj** [comment]
Ok, I might take a closer look at that.

**Comment by myii** [comment]
@dafyddj That would be helpful, thanks.

**Comment by MSeven** [comment]
.vagrant is required to ignore the working folder of the VM manager. 
top.sls is ignored, because in the specific Vagrant setup script, the pillar.example is copied to top.sls to be used as a kind of default/test config.
The basic idea was to use Vagrant to create and initialize a throwaway VM that can be used to test and develop the formula with minimal extra effort. 

If you don't plan to use a similar setup (which would require a Vagrantfile) you can simply remove these two lines from .gitignore.

To be honest, since i am not very involved in the development of the formula, i don't know how much this system is used and therefore cant really judge if it is at all worthwhile to include in the repo in the first place.

**Comment by myii** [comment]
@MSeven Thanks for the reply, this formula here is used to manage 60+ formulas under the SaltStack Formulas organisation, so changes we make here are propagated everywhere.  We just want to clear up these issues so that we can have a common `.gitignore` across the org.  With your feedback, I'm sure we can get closer to that result.  My general feeling was to use your additions anyway.

**Comment by dafyddj** [comment]
Ok, so this is testing in Vagrant outside of Kitchen.
It seems to be a legacy dev/test method that isn't really needed now that we have pretty solidly settled on testing in Kitchen.

**Comment by myii** [comment]
@dafyddj Since the `salt-formula` still has the legacy Vagrant testing, let's leave the TOFS override for that formula.  As for the rest, we'll use your latest addition and propagate that everywhere.  What do you think?

**Comment by dafyddj** [comment]
Sounds good to me!

**Comment by myii** [comment]
@dafyddj Propagating via. #132 right now.

**Pull request merged**
